version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432" # default postgres port
