name: Check

on:
  push:
    branches:
      - main # assumes GitHub default branch name
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "node_version=$(cat .github/nodejs.version)" >> $GITHUB_ENV

      - name: "use node ${{ env.node_version }}"
        uses: actions/setup-node@v4
        with:
          node-version: "${{ env.node_version }}"

      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-nodemodules
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm clean-install

      - name: Lint check
        run: npm run lint

      - name: Format check
        run: npm run prettier

      - name: Unit & Integration tests
        run: npm run test
